CREATE TABLE mfa_tokens (
    id_mfa_token BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(255) NOT NULL,
    token        VARCHAR(255) NOT NULL UNIQUE,
    username     VARCHAR(255) NOT NULL,
    is_used      BOOLEAN      NOT NULL,
    valid_until  TIMESTAMP,
    created_at   TIMESTAMP,
    used_at      TIMESTAMP
);

CREATE TABLE organizations (
    id_organization BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    external_code   VARCHAR(255) UNIQUE,
    uuid            UUID         NOT NULL UNIQUE,
    is_active       BOOLEAN      NOT NULL,
    is_deleted      BOOLEAN      NOT NULL,
    created_by      VARCHAR(255),
    created_at      TIMESTAMP,
    updated_by      VARCHAR(255),
    updated_at      TIMESTAMP
);

CREATE TABLE users (
    id_user             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID         NOT NULL UNIQUE,
    name                VARCHAR(255) NOT NULL,
    authentication_type VARCHAR(255),
    username            VARCHAR(255) NOT NULL UNIQUE,
    password            VARCHAR(255),
    salt                VARCHAR(255),
    email               VARCHAR(255) NOT NULL UNIQUE,
    is_active           BOOLEAN      NOT NULL,
    is_deleted          BOOLEAN      NOT NULL,
    created_by          VARCHAR(255),
    created_at          TIMESTAMP,
    updated_by          VARCHAR(255),
    updated_at          TIMESTAMP
);

CREATE TABLE password_tokens (
    id_password_token BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token             VARCHAR(255) NOT NULL UNIQUE,
    is_used           BOOLEAN      NOT NULL,
    id_user           BIGINT       NOT NULL REFERENCES users (id_user),
    valid_until       TIMESTAMP,
    created_by        VARCHAR(255),
    created_at        TIMESTAMP,
    updated_by        VARCHAR(255),
    updated_at        TIMESTAMP
);

CREATE TABLE systems (
    id_system       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_organization BIGINT       NOT NULL REFERENCES organizations (id_organization),
    external_code   VARCHAR(255) UNIQUE,
    description     VARCHAR(255),
    url             VARCHAR(255),
    scopes          VARCHAR(255),
    uuid            UUID         NOT NULL UNIQUE,
    is_active       BOOLEAN      NOT NULL,
    is_deleted      BOOLEAN      NOT NULL,
    created_by      VARCHAR(255),
    created_at      TIMESTAMP,
    updated_by      VARCHAR(255),
    updated_at      TIMESTAMP
);

CREATE TABLE access_logs (
    id_access_log  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user        BIGINT REFERENCES users (id_user),
    attempted_at   TIMESTAMP,
    attempt_result VARCHAR(255),
    ip_host        VARCHAR(255),
    id_system      BIGINT REFERENCES systems (id_system)
);

CREATE TABLE actions (
    cd_action   VARCHAR(255) PRIMARY KEY,
    action_type VARCHAR(255),
    id_system   BIGINT  NOT NULL REFERENCES systems (id_system),
    is_active   BOOLEAN NOT NULL,
    is_deleted  BOOLEAN NOT NULL,
    created_by  VARCHAR(255),
    created_at  TIMESTAMP,
    updated_by  VARCHAR(255),
    updated_at  TIMESTAMP
);

CREATE TABLE roles (
    id_role         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_system       BIGINT  NOT NULL REFERENCES systems (id_system),
    id_organization BIGINT  NOT NULL REFERENCES organizations (id_organization),
    system_role     VARCHAR(255),
    external_role   VARCHAR(255),
    role_type       VARCHAR(255),
    uuid            UUID    NOT NULL UNIQUE,
    is_active       BOOLEAN NOT NULL,
    is_deleted      BOOLEAN NOT NULL,
    created_by      VARCHAR(255),
    created_at      TIMESTAMP,
    updated_by      VARCHAR(255),
    updated_at      TIMESTAMP
);

CREATE TABLE role_actions (
    id_role_action BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_role        BIGINT  NOT NULL REFERENCES roles (id_role),
    cd_action      BIGINT  NOT NULL REFERENCES actions (cd_action),
    is_active      BOOLEAN NOT NULL,
    is_deleted     BOOLEAN NOT NULL,
    created_by     VARCHAR(255),
    created_at     TIMESTAMP,
    updated_by     VARCHAR(255),
    updated_at     TIMESTAMP
);

CREATE TABLE role_users (
    id_role_user BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_role      BIGINT  NOT NULL REFERENCES roles (id_role),
    id_user      BIGINT  NOT NULL REFERENCES users (id_user),
    is_active    BOOLEAN NOT NULL,
    is_deleted   BOOLEAN NOT NULL,
    created_by   VARCHAR(255),
    created_at   TIMESTAMP,
    updated_by   VARCHAR(255),
    updated_at   TIMESTAMP
);
